name: warshatkom
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get:
  http:
  auto_size_text:
  badges:
  animated_text_kit:
  firebase_core:
  firebase_messaging:
  shared_preferences:
  google_nav_bar:
  fl_country_code_picker:
  smooth_page_indicator:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons:

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/logo/icon.png'

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/logo/
    - assets/gif/
    - assets/icons/
    - assets/icons/
    - assets/temp/

  fonts:
    - family: Changa
      fonts:
        - asset: assets/fonts/Changa.ttf
    - family: CodecPro
      fonts:
        - asset: assets/fonts/CodecPro-Regular.ttf